/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.BoletaDAO;
import clases.ClienteDAO;
import clases.ConexionBD;
import clases.DetalleDAO;
import clases.DetallePedido;
import clases.PedidoDAO;
import clases.UsuarioDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JEREMY
 */
public class RegistrarPedido extends javax.swing.JPanel {

    
    /**
     * Creates new form registrar_pedido
     */
    DetallePedido dto;
    DetalleDAO det;
    ArrayList<DetallePedido> list = new ArrayList<DetallePedido>();
    int fila;
    private boolean estoyOcupado;
    String iduser;
    public RegistrarPedido() {
        initComponents();
        dto = new DetallePedido();
        det= new DetalleDAO();
        PanelM.setVisible(false);
        panelped.setVisible(false);
        PanelDCli.setVisible(false);
        PanelArti.setVisible(false);
        txtFechaa.setText(det.hoy());
        estoyOcupado = false;
         genped.setVisible(false);
        llenarDescripcion();
        llenarDescripcion1();
        
    }
    private void llenarDescripcion(){
		
		estoyOcupado = true;	
		cbodetarti.removeAllItems();
		for (DetallePedido det : det.TraerDes()) {
			cbodetarti.addItem(det.getDescripcion());
		}
		cbodetarti.setSelectedIndex(-1);
		
		estoyOcupado = false;
	}
        private void llenarDescripcion1(){
		
		estoyOcupado = true;	
		cbodetarti1.removeAllItems();
		for (DetallePedido det : det.TraerDes()) {
			cbodetarti1.addItem(det.getDescripcion());
		}
		cbodetarti1.setSelectedIndex(-1);
		
		estoyOcupado = false;
	}
     String fechassal(){
    Date fes=date1.getDate();
    SimpleDateFormat cfe = new SimpleDateFormat("dd-MM-yyyy");
    return cfe.format(fes);
    }
   
      
         void muestra3(){
             DefaultTableModel dt = (DefaultTableModel) tabla1.getModel();
   
    dt.setRowCount(0);
    for(DetallePedido x:det.LisPedido(txtcodp.getText())){
    Object v[]={x.getCoda(),x.getDescripcion(),x.getCantidad(),x.getPrecio(),x.getSubtotal()};
    dt.addRow(v);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtBusCli = new javax.swing.JTextField();
        btnBusCli = new javax.swing.JLabel();
        PanelArti = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        cbodetarti = new javax.swing.JComboBox<>();
        PanelM = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        txtcan1 = new javax.swing.JTextField();
        txtp1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        cambio1 = new javax.swing.JLabel();
        cbodetarti1 = new javax.swing.JComboBox<>();
        delete = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        Finalizar = new javax.swing.JLabel();
        modify = new javax.swing.JLabel();
        addcli = new javax.swing.JLabel();
        PanelDCli = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        genped = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelped = new javax.swing.JPanel();
        txtnume = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtFechaa = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        txtestdo = new javax.swing.JTextField();
        GenP = new javax.swing.JLabel();
        txtcodp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 580));

        jPanel1.setBackground(new java.awt.Color(0, 191, 197));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jLabel20.setBackground(new java.awt.Color(150, 150, 150));
        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Buscar cliente");
        jLabel20.setOpaque(true);

        txtBusCli.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtBusCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        btnBusCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBusCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_cliente.png"))); // NOI18N
        btnBusCli.setToolTipText("");
        btnBusCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusCliMouseClicked(evt);
            }
        });

        PanelArti.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(150, 150, 150));
        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Descripción");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel4.setOpaque(true);

        txtPrecio.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtPrecio.setEnabled(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(150, 150, 150));
        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Precio S/.");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel12.setOpaque(true);

        add.setBackground(new java.awt.Color(0, 191, 197));
        add.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        add.setText("Agregar");
        add.setToolTipText("");
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(150, 150, 150));
        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cantidad");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel10.setOpaque(true);

        txtCant.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtCant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });

        tabla1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla1.setSelectionBackground(new java.awt.Color(0, 191, 197));
        jScrollPane1.setViewportView(tabla1);

        cbodetarti.setBackground(new java.awt.Color(0, 191, 197));
        cbodetarti.setForeground(new java.awt.Color(255, 255, 255));
        cbodetarti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbodetarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodetartiActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(150, 150, 150));
        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Descripción");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel13.setOpaque(true);

        txtdes.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtdes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtdes.setEnabled(false);

        jLabel14.setBackground(new java.awt.Color(150, 150, 150));
        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cantidad");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel14.setOpaque(true);

        txtcan.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtcan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtcan.setEnabled(false);

        jLabel15.setBackground(new java.awt.Color(150, 150, 150));
        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Precio S/.");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel15.setOpaque(true);

        txtp.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtp.setEnabled(false);

        txtcan1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtcan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        txtp1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        txtp1.setEnabled(false);

        jLabel16.setText("Actual");

        jLabel17.setText("Nuevo");

        cancel.setBackground(new java.awt.Color(0, 191, 197));
        cancel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancelar");
        cancel.setToolTipText("");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        cancel.setOpaque(true);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        cambio1.setBackground(new java.awt.Color(0, 191, 197));
        cambio1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cambio1.setForeground(new java.awt.Color(255, 255, 255));
        cambio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambio1.setText("Cambiar");
        cambio1.setToolTipText("");
        cambio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        cambio1.setOpaque(true);
        cambio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambio1MouseClicked(evt);
            }
        });

        cbodetarti1.setBackground(new java.awt.Color(0, 191, 197));
        cbodetarti1.setForeground(new java.awt.Color(255, 255, 255));
        cbodetarti1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbodetarti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodetarti1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMLayout = new javax.swing.GroupLayout(PanelM);
        PanelM.setLayout(PanelMLayout);
        PanelMLayout.setHorizontalGroup(
            PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMLayout.createSequentialGroup()
                        .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMLayout.createSequentialGroup()
                                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcan1)
                                    .addComponent(cbodetarti1, 0, 93, Short.MAX_VALUE)))
                            .addGroup(PanelMLayout.createSequentialGroup()
                                .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel17)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMLayout.createSequentialGroup()
                                .addComponent(cambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
        );
        PanelMLayout.setVerticalGroup(
            PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbodetarti1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(cambio1))
                .addGap(23, 23, 23))
        );

        delete.setBackground(new java.awt.Color(0, 191, 197));
        delete.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        delete.setText("Eliminar");
        delete.setToolTipText("");
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        delete.setOpaque(true);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 191, 197));
        clear.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        clear.setText("Limpiar");
        clear.setToolTipText("");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        clear.setOpaque(true);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        Finalizar.setBackground(new java.awt.Color(0, 191, 197));
        Finalizar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Finalizar.setForeground(new java.awt.Color(255, 255, 255));
        Finalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Finalizar.setText("Finalizar");
        Finalizar.setToolTipText("");
        Finalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        Finalizar.setOpaque(true);
        Finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarMouseClicked(evt);
            }
        });

        modify.setBackground(new java.awt.Color(0, 191, 197));
        modify.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        modify.setForeground(new java.awt.Color(255, 255, 255));
        modify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        modify.setText("Modificar");
        modify.setToolTipText("");
        modify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        modify.setOpaque(true);
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelArtiLayout = new javax.swing.GroupLayout(PanelArti);
        PanelArti.setLayout(PanelArtiLayout);
        PanelArtiLayout.setHorizontalGroup(
            PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelArtiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArtiLayout.createSequentialGroup()
                        .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelArtiLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbodetarti, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelArtiLayout.createSequentialGroup()
                                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCant, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)))
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelArtiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelArtiLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(PanelArtiLayout.createSequentialGroup()
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
        );
        PanelArtiLayout.setVerticalGroup(
            PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArtiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArtiLayout.createSequentialGroup()
                        .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbodetarti, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelM, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PanelArtiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addcli.setBackground(new java.awt.Color(0, 191, 197));
        addcli.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        addcli.setForeground(new java.awt.Color(255, 255, 255));
        addcli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcli.setText("Añadir Cliente");
        addcli.setToolTipText("");
        addcli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        addcli.setOpaque(true);
        addcli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcliMouseClicked(evt);
            }
        });

        PanelDCli.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(150, 150, 150));
        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dirección");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel8.setOpaque(true);

        txtApe.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtApe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        jLabel1.setBackground(new java.awt.Color(150, 150, 150));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombres");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel1.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(150, 150, 150));
        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Apellidos");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel5.setOpaque(true);

        txtTel.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        jLabel9.setBackground(new java.awt.Color(150, 150, 150));
        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("E-mail");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel9.setOpaque(true);

        txtNom.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        jLabel7.setBackground(new java.awt.Color(150, 150, 150));
        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DNI");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel7.setOpaque(true);

        txtDir.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        genped.setBackground(new java.awt.Color(0, 191, 197));
        genped.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        genped.setForeground(new java.awt.Color(255, 255, 255));
        genped.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genped.setText("Generar Pedido");
        genped.setToolTipText("");
        genped.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        genped.setOpaque(true);
        genped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genpedMouseClicked(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        jLabel6.setBackground(new java.awt.Color(150, 150, 150));
        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Teléfono");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel6.setOpaque(true);

        txtDni.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_datos_cliente.png"))); // NOI18N

        javax.swing.GroupLayout PanelDCliLayout = new javax.swing.GroupLayout(PanelDCli);
        PanelDCli.setLayout(PanelDCliLayout);
        PanelDCliLayout.setHorizontalGroup(
            PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDCliLayout.createSequentialGroup()
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDCliLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(genped, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelDCliLayout.setVerticalGroup(
            PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genped, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtnume.setText("#");
        txtnume.setEnabled(false);

        jLabel18.setBackground(new java.awt.Color(150, 150, 150));
        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Fecha de pedido");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel18.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(150, 150, 150));
        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Fecha de recojo");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel21.setOpaque(true);

        txtFechaa.setEnabled(false);

        jLabel19.setBackground(new java.awt.Color(150, 150, 150));
        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Estado pedido");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 150)));
        jLabel19.setOpaque(true);

        txtestdo.setText("EN CURSO");
        txtestdo.setEnabled(false);

        GenP.setBackground(new java.awt.Color(0, 191, 197));
        GenP.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        GenP.setForeground(new java.awt.Color(255, 255, 255));
        GenP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenP.setText("Añadir articulos");
        GenP.setToolTipText("");
        GenP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 191, 197)));
        GenP.setOpaque(true);
        GenP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelpedLayout = new javax.swing.GroupLayout(panelped);
        panelped.setLayout(panelpedLayout);
        panelpedLayout.setHorizontalGroup(
            panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpedLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtestdo))
                    .addGroup(panelpedLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaa))
                    .addGroup(panelpedLayout.createSequentialGroup()
                        .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelpedLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelpedLayout.createSequentialGroup()
                                .addComponent(txtnume, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcodp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GenP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelpedLayout.setVerticalGroup(
            panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnume)
                    .addComponent(txtcodp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelpedLayout.createSequentialGroup()
                        .addComponent(txtFechaa)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtestdo, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(GenP)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelDCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addcli, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelArti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(616, 616, 616))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBusCli, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(btnBusCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelDCli, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelped, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelArti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyMouseClicked

        fila=tabla1.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null,"Elija una fila");
            return; 
        }
        PanelM.setVisible(true);
        txtdes.setText(tabla1.getValueAt(fila, 1).toString());
        txtcan.setText(tabla1.getValueAt(fila, 2).toString());
        txtp.setText(tabla1.getValueAt(fila, 3).toString());
                           
    }//GEN-LAST:event_modifyMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       
            
        det.setDescripcion(cbodetarti.getSelectedItem().toString());
        det.setCantidad(Integer.parseInt(txtCant.getText()));
        det.setPrecio(Double.parseDouble(txtPrecio.getText()));
        det.setCodped(txtcodp.getText());
        det.setSubtotal(Integer.parseInt(txtCant.getText())*Double.parseDouble(txtPrecio.getText()));
              
        if(det.AñadirArticulo()==1){
            JOptionPane.showMessageDialog(null, "Articulo añadido correctamente.");           
        }
        muestra3();
    }//GEN-LAST:event_addMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
      fila=tabla1.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null,"Elija una fila");
            return; 
        }
        String dato=tabla1.getValueAt(fila, 0).toString();
   
        det.Anula(dato);
        muestra3();
   
    }//GEN-LAST:event_deleteMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        DefaultTableModel tb = (DefaultTableModel) tabla1.getModel();
        int a = tabla1.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
        det.deleteall();
        String dato=txtcodp.getText();
              
   
        det.AnulaAll(dato);
        JOptionPane.showMessageDialog(null,"Se han borrado los articulos");
        muestra3();
    }//GEN-LAST:event_clearMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        PanelM.setVisible(false);
    }//GEN-LAST:event_cancelMouseClicked

    private void cambio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambio1MouseClicked
        // TODO add your handling code here
         fila=tabla1.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null,"Elija una fila.");
            return; 
        }
    String dato=tabla1.getValueAt(fila, 0).toString();
                           det.setDescripcion(cbodetarti1.getSelectedItem().toString());
                           det.setCantidad(Integer.parseInt(txtcan1.getText()));
                           det.setPrecio(Double.parseDouble(txtp1.getText()));
                           det.setCoda(Integer.parseInt(dato));
                           
                           if(det.Cambia()==1){
            JOptionPane.showMessageDialog(null, "Articulo modificado correctamente.");
           
        }
         muestra3();
        PanelM.setVisible(false);        
    }//GEN-LAST:event_cambio1MouseClicked

    private void btnBusCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusCliMouseClicked
        ClienteDAO cd=new ClienteDAO();
        cd.setDni(Integer.parseInt(txtBusCli.getText()));
        if(cd.BuscarCliente()==1){
            cd.DatosCliente();
          txtNom.setText(cd.getNom());
          txtApe.setText(cd.getApe());
          txtDni.setText(Integer.toString(cd.getDni()));
          txtTel.setText(Integer.toString(cd.getTel()));
          txtDir.setText(cd.getDir());
          txtEmail.setText(cd.getEmail());
          genped.setVisible(true);
          PanelDCli.setVisible(true);
        }
       
   
    }//GEN-LAST:event_btnBusCliMouseClicked

    private void GenPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenPMouseClicked
        // TODO add your handling code here:
          PedidoDAO ou=new PedidoDAO();
          ou.setCodp(txtcodp.getText());
        ou.setFechae(txtFechaa.getText());
        ou.setFechar(fechassal());
        ou.setEstado(txtestdo.getText());
        ou.setDni(txtDni.getText());        
        if(ou.AñadirPedido()==1){
            JOptionPane.showMessageDialog(null, "Pedido añadido correctamente.");
          PanelArti.setVisible(true);
        }
    }//GEN-LAST:event_GenPMouseClicked

    private void genpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genpedMouseClicked
        // TODO add your handling code here:
        panelped.setVisible(true);
          ConexionBD cn=new ConexionBD();
        Connection con;
        PreparedStatement ps;
        ResultSet rs;
        
        try{
            con=cn.Conexion();
            String sql="exec generar_codped";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
           
                 while (rs.next()) {
               
                txtcodp.setText(rs.getString(1));
                 }
            
        }catch(Exception e){        
        }
    }//GEN-LAST:event_genpedMouseClicked

    private void cbodetartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodetartiActionPerformed

        if (estoyOcupado || cbodetarti.getSelectedIndex() == -1) {
            return;
        }
        estoyOcupado = true;

        String pre = cbodetarti.getSelectedItem().toString();
        det.MostrarPrecio(pre);

        txtPrecio.setText("" + det.getPrecio());

        estoyOcupado = false;
    }//GEN-LAST:event_cbodetartiActionPerformed

    private void cbodetarti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodetarti1ActionPerformed
        // TODO add your handling code here:
         if (estoyOcupado || cbodetarti1.getSelectedIndex() == -1) {
            return;
        }
        estoyOcupado = true;

        String pre = cbodetarti1.getSelectedItem().toString();
        det.MostrarPrecio(pre);

        txtp1.setText("" + det.getPrecio());

        estoyOcupado = false;
    }//GEN-LAST:event_cbodetarti1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void addcliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcliMouseClicked
        // TODO add your handling code here:
           NewCliente ce=new NewCliente();
        ce.setVisible(true);
              ce.setSize(410,560);
    ce.setLocationRelativeTo(null);
     
        
    }//GEN-LAST:event_addcliMouseClicked

    private void FinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarMouseClicked
        BoletaDAO bdao=new BoletaDAO();
        UsuarioDAO udao=new UsuarioDAO();
        Principal pri=new Principal();
        iduser=pri.iduser;
        if(bdao.GenCodBoleta()==1){
            bdao.setFecemi(txtFechaa.getText());
            udao.setNombres(iduser);
            bdao.setIdusuario(udao.IdUsuario());
            bdao.setPretotal(det.pretotal());
            bdao.setCodped(txtcodp.getText());
            bdao.AñadirBoleta();
        } 
        
        try{
        ConexionBD cn=new ConexionBD();
        Connection con=cn.Conexion();
        
        JasperReport comprobante=null;
        
        String path="src\\reportes\\ComprobanteDePago.jasper";
        
        Map parametro=new HashMap();
        
        parametro.put("codped",txtcodp.getText());
        
        comprobante=(JasperReport)JRLoader.loadObjectFromFile(path);
        
        JasperPrint jprint=JasperFillManager.fillReport(path,parametro,con);
        
        JasperViewer view=new JasperViewer(jprint,false);
        
        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        view.setTitle("Imprimir boleta de pago");
        
        view.setVisible(true);
        }catch (HeadlessException | JRException ex) {
            Logger.getLogger(RegistrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        PanelArti.setVisible(false);
        PanelDCli.setVisible(false);
        panelped.setVisible(false);
        txtBusCli.setText("");
    }//GEN-LAST:event_FinalizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Finalizar;
    private javax.swing.JLabel GenP;
    private javax.swing.JPanel PanelArti;
    private javax.swing.JPanel PanelDCli;
    private javax.swing.JPanel PanelM;
    private javax.swing.JLabel add;
    private javax.swing.JLabel addcli;
    private javax.swing.JLabel btnBusCli;
    private javax.swing.JLabel cambio1;
    private javax.swing.JLabel cancel;
    private javax.swing.JComboBox<String> cbodetarti;
    private javax.swing.JComboBox<String> cbodetarti1;
    private javax.swing.JLabel clear;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel genped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel modify;
    private javax.swing.JPanel panelped;
    public javax.swing.JTable tabla1;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtBusCli;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaa;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtcan;
    private javax.swing.JTextField txtcan1;
    private javax.swing.JLabel txtcodp;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtestdo;
    private javax.swing.JTextField txtnume;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtp1;
    // End of variables declaration//GEN-END:variables
}
